name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: priyamchandra/my-dash-app:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Deploy Docker image to EC2
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          # SSH into your EC2 instance
          ssh -o StrictHostKeyChecking=no ec2-user@16.171.41.101 << 'EOF'

          # Stop the currently running container (if any)
          docker stop practical_merkle || true
          
          # Remove the existing container (if any)
          docker rm practical_merkle || true

          # Pull the latest Docker image from Docker Hub
          docker pull priyamchandra/my-dash-app:latest

          # Run the Docker container
          docker run -d -p 8050:8050 --name practical_merkle priyamchandra/my-dash-app:latest

          EOF
