name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: priyamchandra/my-dash-app:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Deploy to EC2
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: 'your-aws-region'
        INSTANCE_ID: 'your-ec2-instance-id'
        DOCKER_IMAGE: 'priyamchandra/my-dash-app:latest'
      script: |
          docker login -u AWS -p $AWS_SECRET_ACCESS_KEY https://aws-account-id.dkr.ecr.your-region.amazonaws.com
          docker pull aws-account-id.dkr.ecr.your-region.amazonaws.com/your-docker-image:latest
          docker run -d -p 80:80 aws-account-id.dkr.ecr.your-region.amazonaws.com/your-docker-image:latest
