name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: priyamchandra/my-dash-app:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Deploy to EC2
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: 'your-aws-region'
        INSTANCE_ID: 'your-ec2-instance-id'
        DOCKER_IMAGE: 'priyamchandra/my-dash-app:latest'
      run: |
        ssh -o StrictHostKeyChecking=no -i "Docker_key.pem" ec2-user@${{ secrets.EC2_PUBLIC_IP }} << 'EOF'
          docker pull priyamchandra/my-dash-app:latest
          docker stop my-dash-app || true
          docker rm my-dash-app || true
          docker run -d -p 8050:8050 --name my-dash-app priyamchandra/my-dash-app:latest
        EOF
